### PR TITLE
Allow use of user-defined error types in rusqlite migrations.

### PR DESCRIPTION
**Pull request by nuttycom**
This builds atop #13 to permit user-defined error types in rusqlite migrations. This is useful for migrations that may need to perform more complex operations that can fail in ways that don't fit correctly into rusqlite's error type.

### CODE REVIEW

**Review by daira — APPROVED** [review]
Untested ACK b3f7c8a3abb69b67d68258ae5284c5743bdb380b

**Comment by aschampion** [comment]
doctest failing, possibly due to a missing import.

The generic param and that this makes the rusqlite adapter more different from the postgres one aren't great, but I think it's a reasonable workaround since the underlying problem is that there isn't an ergonomic way for migrations or adapters to have application-specific errors as currently written.

I'm fine with merging and releasing as version 0.2 with the expectation I'll probably change error handling later in another breaking version.

**Comment by nuttycom** [comment]
Updated & rebased to fix the CI failures.

**Comment by aschampion** [comment]
Thanks @nuttycom! I'll publish 0.2 tomorrow.

**Comment by nuttycom** [comment]
> Thanks @nuttycom! I'll publish 0.2 tomorrow.

Thank you!

**Comment by aschampion** [comment]
Published, let me know if you encounter any problems.

**Pull request merged**
